---
# Variable setup
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks
- include: setup-RedHat.yml
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- include: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- include: setup-Fedora.yml
  when: ansible_distribution == 'Fedora'

- include: setup-Debian.yml
  when: ansible_distribution == 'Debian'

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Configuration tasks
- name: link config for openresty to nginx
  file:
    state: link
    src: "{{ openresty_conf_path }}"
    path: "{{ nginx_conf_path }}"

- debug: var=ansible_service_mgr

- name: remove any existing nginx init script
  file:
    state: absent
    path: /etc/init.d/nginx

- name: link openresty init script as nginx for service
  file:
    state: link
    src: /etc/init.d/openresty
    path: /etc/init.d/nginx

- name: create nginx service for systemd
  template:
    src: etc/systemd/system/nginx.service.j2
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'

- name: create standard nginx directories
  file:
    state: directory
    path: "{{ nginx_conf_path }}/{{ item }}"
  with_items:
    - conf.d
    - sites-enabled
    - sites-available

- name: install default nginx configuration
  template:
    src: etc/nginx/{{ item }}.j2
    dest: "{{ nginx_conf_path }}/{{ item }}"
  with_items:
    - nginx.conf
    - conf.d/defaults
  notify: restart nginx
